basePath: /api/v1
host: localhost:8080
info:
  contact: {}
  description: This is a sample Gin REST API with Swagger documentation
  title: Gin REST API Example
  version: "1.0"
paths:
  /users:
    get:
      consumes:
      - application/json
      description: Fetch all users from the database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              additionalProperties:
                type: string
              type: object
            type: array
      summary: Get all users
      tags:
      - users
  /users/{id}:
    get:
      consumes:
      - application/json
      description: Fetch a specific user using an ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: User not found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get user by ID
      tags:
      - users
swagger: "2.0"
